# Generated by Django 5.2.2 on 2025-11-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo/Descartado')], default='disponivel', max_length=20),
        ),
    ]
